title: Mountaineering Documentation
description: This website contains documentation about various mountaineering
  equipment and techniques. This is knowledge we have collected from our
  experience, and schools and seminars we have attended.
theme: just-the-docs

url: https://cspavlou.github.io/mountaineering/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
